"""linux commands drop code change description to text

Revision ID: 483bae604bc4
Revises: 102fa7c25663
Create Date: 2019-03-22 20:46:33.710099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '483bae604bc4'
down_revision = '102fa7c25663'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("linux_command") as batch_op:
        batch_op.drop_column('code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('linux_command', sa.Column('code', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###
